var queries = {
    INSERT_DATA_USER : 'INSERT INTO USERDATA (USER_ID, NAME, CODE, CAPITAL, REGION, POPULATION, NUMERICCODE, FLAG) VALUES ?',
    INSERT_DATA_RAW : 'INSERT INTO RAWDATAINPUT (JSONINPUTREQUEST, SYSTEMMASTERID, RAWDATASTATUSID, CREATEDDATE) VALUES ?',
}

module.exports = queries;